# Hyprland core settings
# Read https://hydeproject.pages.dev/en/configuring/hyprland/ for the full documentation.
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/keybind.conf
source = ~/.config/hypr/configs/programs.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/monitor.conf
source = ~/.config/hypr/configs/look.conf
source = ~/.config/hypr/configs/windowrules.conf