font-family = "Fira Code"
mouse-hide-while-typing = true
copy-on-select = clipboard
cursor-style = underline
background-opacity = 0.9
window-padding-x = 12
window-padding-y = 4
window-height = 33
window-width = 100